[package]
name = "solana-memecoin-landing"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2.12.2"
napi-derive = "2.12.2"

[build-dependencies]
napi-build = "2.0.1"

